name: Deploy Django App to Fly.io

on:
  push:
    branches:
      - main  # Altere se seu branch de produção for diferente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Ajuste para a versão que seu projeto usa

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd mangasV2
          pip install -r requirements.txt

      - name: Set up Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: |
          pwd
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
